/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import pack.control.c_koneksi;
import pack.control.controllerToko;
import pack.model.m_toko;

/**
 *
 * @author dani
 */
public class home extends javax.swing.JFrame {
    controllerToko ctoko;
    List<m_toko>listdata = new ArrayList<>();
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        ctoko = new controllerToko (this);
        ctoko.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtadmin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledata = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        Simpan = new javax.swing.JButton();
        Ubah = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        Bersihkan = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txtkode = new javax.swing.JTextField();
        cbjenis = new javax.swing.JComboBox();
        cbkategoribarang = new javax.swing.JComboBox();
        txtnama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbcarikategori = new javax.swing.JComboBox();
        Cari = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Admin Toko :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(29, 44, 82, 17);
        jPanel1.add(txtadmin);
        txtadmin.setBounds(121, 33, 115, 41);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("DATA BARANG DITOKO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(329, 52, 192, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 100);

        jPanel2.setBackground(new java.awt.Color(0, 255, 51));
        jPanel2.setLayout(null);

        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori", "Packaging", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabledata);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 480, 210);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(60, 310, 530, 230);

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));
        jPanel3.setLayout(null);

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        jPanel3.add(Simpan);
        Simpan.setBounds(50, 10, 107, 30);

        Ubah.setText("Ubah");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });
        jPanel3.add(Ubah);
        Ubah.setBounds(50, 40, 107, 30);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jPanel3.add(Keluar);
        Keluar.setBounds(50, 130, 107, 30);

        Bersihkan.setText("Bersihkan");
        Bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BersihkanActionPerformed(evt);
            }
        });
        jPanel3.add(Bersihkan);
        Bersihkan.setBounds(50, 70, 107, 30);

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel3.add(Hapus);
        Hapus.setBounds(50, 100, 107, 30);

        jPanel5.setBackground(new java.awt.Color(0, 204, 255));
        jPanel5.setLayout(null);

        jButton7.setText("Simpan");
        jPanel5.add(jButton7);
        jButton7.setBounds(50, 10, 107, 30);

        jButton8.setText("Ubah");
        jPanel5.add(jButton8);
        jButton8.setBounds(50, 40, 107, 30);

        jButton9.setText("Keluar");
        jPanel5.add(jButton9);
        jButton9.setBounds(50, 130, 107, 30);

        jButton10.setText("Bersihkan");
        jPanel5.add(jButton10);
        jButton10.setBounds(50, 70, 107, 30);

        jButton11.setText("Hapus");
        jPanel5.add(jButton11);
        jButton11.setBounds(50, 100, 107, 30);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(580, 100, 210, 170);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(600, 100, 210, 170);

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));
        jPanel4.setLayout(null);

        jLabel3.setText("Harga");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 142, 90, 23);

        jLabel4.setText("Kode Barang ");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 11, 73, 26);

        jLabel5.setText("Nama Barang");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 43, 73, 26);

        jLabel6.setText("Kategori Barang");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 75, 90, 26);

        jLabel7.setText("Jenis Packaging");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 107, 90, 29);
        jPanel4.add(txtharga);
        txtharga.setBounds(100, 130, 340, 30);
        jPanel4.add(txtkode);
        txtkode.setBounds(100, 10, 341, 30);

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Makan Disini", "Bungkus (kardus)", "Bungkus (Sterofom)", "Bungkus (Plastik)" }));
        jPanel4.add(cbjenis);
        cbjenis.setBounds(100, 100, 340, 30);

        cbkategoribarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Makanan", "Sate", "Bakso", "Tahu Telor" }));
        jPanel4.add(cbkategoribarang);
        cbkategoribarang.setBounds(100, 70, 340, 30);
        jPanel4.add(txtnama);
        txtnama.setBounds(100, 40, 340, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(60, 100, 470, 170);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pencarian Berdasarkan Kategor Makanan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 270, 250, 40);

        cbcarikategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Makanan", "Sate", "Bakso", "Tahu Telor" }));
        getContentPane().add(cbcarikategori);
        cbcarikategori.setBounds(350, 280, 140, 30);

        Cari.setText("Cari");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });
        getContentPane().add(Cari);
        Cari.setBounds(510, 280, 90, 30);

        jPanel6.setBackground(new java.awt.Color(0, 204, 255));
        jPanel6.setLayout(null);
        getContentPane().add(jPanel6);
        jPanel6.setBounds(600, 310, 210, 230);

        setBounds(0, 0, 832, 585);
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        ctoko.SimpanData();
        ctoko.isiTable();
    }//GEN-LAST:event_SimpanActionPerformed

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
        ctoko.Ubah();
        ctoko.isiTable();
    }//GEN-LAST:event_UbahActionPerformed

    private void BersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihkanActionPerformed
        // TODO add your handling code here:
        ctoko.Reset();
    }//GEN-LAST:event_BersihkanActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        ctoko.Hapus();
        ctoko.isiTable();
    }//GEN-LAST:event_HapusActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
        ctoko.CariKategori();
        ctoko.isiTable();
    }//GEN-LAST:event_CariActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String user1 = login.user;
        txtadmin.setText(user1);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bersihkan;
    private javax.swing.JButton Cari;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Simpan;
    private javax.swing.JButton Ubah;
    private javax.swing.JComboBox cbcarikategori;
    private javax.swing.JComboBox cbjenis;
    private javax.swing.JComboBox cbkategoribarang;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabledata;
    private javax.swing.JTextField txtadmin;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

public JTextField getTxtKode(){
        return txtkode;
    }
    public JTextField getTxtNama(){
        return txtnama;
    }
    public JTextField getTxtHarga(){
        return txtharga;
    }
    public JComboBox getCbKategori(){
        return cbkategoribarang;
    }
    public JComboBox getCbJenis(){
        return cbjenis;
    }
    public JComboBox getCbCariKategori(){
        return cbcarikategori;
    }
    public JButton getButtonHapus(){
        return Hapus;
    }
    
    public JButton getButtonBersih(){
        return Bersihkan;
    }
    public JButton getButtonSimpan(){
        return Simpan;
    }
    public JButton getButtonUbah(){
        return Ubah;
    }
    public JButton getButtonKeluar(){
        return Keluar;
    }
    public JTable getTableData(){
        return tabledata;
    }
}